### ISSUE TITLE
[Suggestion] Abstract out growing mechanics and block checks from the grower classes

### ISSUE THREAD

**Issue by oliviathevampire** [Osmiooo/wildmod#126]

**Comment by AViewFromTheTop** [comment]
I have a quick question- do you mean using the same checks for both Sculk&Activator? If so, that'd result in more code clutter, given that the Activator's SculkCheck is different from the normal SculkGrower's check. 
If you mean to do use the same checks with CatalystThreader and the two Grower classes, I'm actually planning to remove CatalystThreader as it simply doesn't work properly anymore. CatalystThreader also needs different growing code because using multiple threads to change any blocks in the world causes the game to crash, so I need an altered version of the growing code for it to work (although this won't matter once I remove it.)

**Comment by MerpisMe** [comment]
> I have a quick question- do you mean using the same checks for both Sculk&Activator? If so, that'd result in code clutter, given that the Activator's SculkCheck is different from the normal SculkGrower's check, I wouldn't see how moving it into another class would improve anything. If you mean to do use the same checks with CatalystThreader and the two Grower classes, I'm actually planning to remove CatalystThreader as it simply doesn't work properly anymore. CatalystThreader also needs different growing code because using multiple threads to change any blocks in the world causes the game to crash, so I need an altered version of the growing code for it to work (although this won't matter once I remove it.) There could be something I'm missing or don't know about, so feel free to correct me. EDIT: I might keep the threaded Activator Growth actually, as that hasn't caused anything to break and frees up a bit of performance.

i believe what was meant here was that we split the activatorgrower into its own thing that gets called upon by sculk sensors and shriekers, and would make it easier for us to let sculk jaws grow in twm+ since it would just use the abstract code

**Comment by oliviathevampire** [comment]
I mostly meant seperate out the duplicated code which is the same between all of the growing stuff mostly.
