### ISSUE TITLE
No cooldown for vibration particle showing near warden

### ISSUE THREAD

**Issue by Superwneg64** [Osmiooo/wildmod#32]
Whenever I'm near the warden, whenever I make noise over and over again, the particles keep on showing.  As opposed to Minecraft live, when there's a cooldown for when those particles can show.  It's easiest seen when you spawn a warden and a bee, the bee keeps on showing those vibration particles, when it should only be doing that every so often.

**Comment by AViewFromTheTop** [comment]
The Warden uses the same cooldown as the Sculk Sensor- there hasn't been any definitive proof that the Warden's cooldown is longer, and keeping the cooldown a little short makes it more challenging to fight the Warden.
I'll keep the issue open in case one of the other team members says otherwise, though.

**Comment by BluePhoenixLOL** [comment]
Closed - Works As Intended
